# Generated by Django 2.0.1 on 2018-02-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_url_id',
            field=models.URLField(unique=True),
        ),
    ]
